[package]
name = "glyim-runtime"
edition.workspace = true
version.workspace = true
[dependencies]
socket2 = "0.5"
libc = "0.2"
glyim-core = { workspace = true }
tracing = { workspace = true }
windows-sys = { version = "0.59", features = [
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
] }

[dev-dependencies]
libc = "0.2"
