//! Runtime support: memory allocation, panic handling, drop glue, ABI stubs.
//!
//! This crate provides the low-level FFI interface used by generated code:
//! - `glyim_alloc` — heap allocation with alignment
//! - `glyim_dealloc` — heap deallocation
//! - `glyim_drop_in_place` — drop glue (currently stubbed)
//! - `glyim_panic` — unrecoverable panic handler

pub use glyim_core::abi::ALIGN_MAX;

use std::alloc::{self, Layout};
use std::sync::atomic::{AtomicBool, Ordering};

/// Allocate memory with the given size and alignment.
///
/// Returns a pointer to the allocated memory, or null if allocation fails.
/// For zero-size allocations, returns a dangling non-null pointer.
///
/// # Safety
///
/// This is an FFI function intended for use by generated code. The caller
/// must ensure that:
/// - `align` is a valid alignment (a power of two, or zero which is treated as 1)
/// - If `size > 0`, the returned pointer must be deallocated with
///   `glyim_dealloc` using the same `size` and `align`
/// - A null return indicates allocation failure (OOM)
#[unsafe(no_mangle)]
pub extern "C" fn glyim_alloc(size: usize, align: usize) -> *mut u8 {
    if size == 0 {
        return std::ptr::NonNull::dangling().as_ptr();
    }
    let layout = match Layout::from_size_align(size, align.max(1)) {
        Ok(l) => l,
        Err(_) => return std::ptr::null_mut(),
    };
    // SAFETY: Layout is validated above. alloc::alloc may return null on OOM,
    // which is a valid return value for this FFI function.
    unsafe { alloc::alloc(layout) }
}

/// Deallocate memory previously allocated by `glyim_alloc`.
///
/// # Safety
///
/// - `ptr` must have been returned by `glyim_alloc` with the same `size` and `align`
/// - `ptr` must not have been already deallocated
/// - The memory pointed to by `ptr` must not be accessed after this call
/// - Passing a null pointer or zero size is safe and results in a no-op
#[unsafe(no_mangle)]
pub unsafe extern "C" fn glyim_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
        return;
    }
    if ptr.is_null() {
        return;
    }
    let layout = match Layout::from_size_align(size, align.max(1)) {
        Ok(l) => l,
        Err(_) => return,
    };
    // SAFETY: Caller guarantees ptr was allocated with the same layout
    // and has not been deallocated.
    unsafe { alloc::dealloc(ptr, layout) }
}

/// Drop a value in place by calling its drop glue.
///
/// # Safety
///
/// - `ptr` must point to a valid, aligned value of the expected type
/// - The value will be dropped; `ptr` must not be used after this call
/// - Passing a null pointer is safe and results in a no-op
///
/// # Stub
///
/// This function is currently a stub — it does NOT call the type-specific
/// destructor. A full implementation will use vtable-based drop glue or
/// monomorphized drop calls generated by the compiler. A warning is emitted
/// on the first non-null call to make the stub visible.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn glyim_drop_in_place(ptr: *mut u8) {
    static DROP_WARNED: AtomicBool = AtomicBool::new(false);

    if !ptr.is_null() && !DROP_WARNED.swap(true, Ordering::Relaxed) {
        tracing::warn!(
            "STUB: glyim_drop_in_place is a stub — type-specific drop glue not yet implemented"
        );
    }
}

/// Panic handler for the runtime.
///
/// Aborts the process immediately. The `msg` and `len` parameters provide
/// the panic message as a UTF-8 byte slice, but are currently unused.
/// A future implementation will print the message before aborting.
///
/// # Safety
///
/// This is an FFI function intended for use by generated code. It never returns.
/// - `msg` should point to valid UTF-8 data of length `len`
/// - `len` should be the exact byte length of the message
#[unsafe(no_mangle)]
pub extern "C" fn glyim_panic(_msg: *const u8, _len: usize) -> ! {
    std::process::abort()
}

#[cfg(test)]
mod tests;
