// This file is automatically generated by combining original tests and new suffix tests
// Original content from main follows:
use crate::Token;
use crate::lexer::lex;
use glyim_span::FileId;
use glyim_syntax::SyntaxKind;
use glyim_test::assert_no_errors;

fn test_lex(source: &str) -> Vec<Token> {
    let file_id = FileId::from_raw(1);
    let result = lex(source, file_id);
    assert_no_errors(&result.diagnostics);
    result.tokens
}

#[test]
fn lex_simple_identifiers() {
    let tokens = test_lex("foo bar _baz");
    assert_eq!(tokens.len(), 3);
    assert_eq!(tokens[0].kind, SyntaxKind::Ident);
    assert_eq!(tokens[0].text, "foo");
    assert_eq!(tokens[1].kind, SyntaxKind::Ident);
    assert_eq!(tokens[1].text, "bar");
    assert_eq!(tokens[2].kind, SyntaxKind::Ident);
    assert_eq!(tokens[2].text, "_baz");
}

#[test]
fn lex_keywords() {
    let tokens = test_lex("fn struct enum if else return");
    let kinds: Vec<_> = tokens.iter().map(|t| t.kind).collect();
    assert_eq!(
        kinds,
        vec![
            SyntaxKind::KwFn,
            SyntaxKind::KwStruct,
            SyntaxKind::KwEnum,
            SyntaxKind::KwIf,
            SyntaxKind::KwElse,
            SyntaxKind::KwReturn,
        ]
    );
}

#[test]
fn lex_integer_literals() {
    let tokens = test_lex("42 0x1A 0b101 0o777 0");
    assert_eq!(tokens.len(), 5);
    for t in &tokens {
        assert_eq!(t.kind, SyntaxKind::IntLit);
    }
    assert_eq!(tokens[0].text, "42");
    assert_eq!(tokens[1].text, "0x1A");
    assert_eq!(tokens[2].text, "0b101");
    assert_eq!(tokens[3].text, "0o777");
    assert_eq!(tokens[4].text, "0");
}

#[test]
fn lex_float_literals() {
    let tokens = test_lex("3.14 1.2e10 0.5E-3");
    assert_eq!(tokens.len(), 3);
    for t in &tokens {
        assert_eq!(t.kind, SyntaxKind::FloatLit);
    }
    assert_eq!(tokens[0].text, "3.14");
    assert_eq!(tokens[1].text, "1.2e10");
    assert_eq!(tokens[2].text, "0.5E-3");
}

#[test]
fn lex_string_and_char() {
    let tokens = test_lex("\"hello\" 'a' \"\\n\"");
    assert_eq!(tokens.len(), 3);
    assert_eq!(tokens[0].kind, SyntaxKind::StringLit);
    assert_eq!(tokens[0].text, "\"hello\"");
    assert_eq!(tokens[1].kind, SyntaxKind::CharLit);
    assert_eq!(tokens[1].text, "'a'");
    assert_eq!(tokens[2].kind, SyntaxKind::StringLit);
    assert_eq!(tokens[2].text, "\"\\n\"");
}

#[test]
fn lex_punctuation() {
    let tokens = test_lex("(){}[] , ; . :: -> =>");
    let kinds: Vec<_> = tokens.iter().map(|t| t.kind).collect();
    assert_eq!(
        kinds,
        vec![
            SyntaxKind::LParen,
            SyntaxKind::RParen,
            SyntaxKind::LBrace,
            SyntaxKind::RBrace,
            SyntaxKind::LBracket,
            SyntaxKind::RBracket,
            SyntaxKind::Comma,
            SyntaxKind::Semicolon,
            SyntaxKind::Dot,
            SyntaxKind::ColonColon,
            SyntaxKind::Arrow,
            SyntaxKind::FatArrow,
        ]
    );
}

#[test]
fn lex_operators() {
    let tokens = test_lex("+ - * / % = == != < > <= >= && || ! ^ << >>");
    let kinds: Vec<_> = tokens.iter().map(|t| t.kind).collect();
    assert_eq!(
        kinds,
        vec![
            SyntaxKind::Plus,
            SyntaxKind::Minus,
            SyntaxKind::Star,
            SyntaxKind::Slash,
            SyntaxKind::Percent,
            SyntaxKind::Eq,
            SyntaxKind::EqEq,
            SyntaxKind::BangEq,
            SyntaxKind::Lt,
            SyntaxKind::Gt,
            SyntaxKind::LtEq,
            SyntaxKind::GtEq,
            SyntaxKind::AndAnd,
            SyntaxKind::OrOr,
            SyntaxKind::Bang,
            SyntaxKind::Caret,
            SyntaxKind::Shl,
            SyntaxKind::Shr,
        ]
    );
}

#[test]
fn lex_line_comment() {
    let tokens = test_lex("foo // comment\nbar");
    assert_eq!(tokens.len(), 2);
    assert_eq!(tokens[0].kind, SyntaxKind::Ident);
    assert_eq!(tokens[0].text, "foo");
    assert_eq!(tokens[1].kind, SyntaxKind::Ident);
    assert_eq!(tokens[1].text, "bar");
}

#[test]
fn lex_block_comment() {
    let tokens = test_lex("foo /* nested /* comment */ */ bar");
    assert_eq!(tokens.len(), 2);
    assert_eq!(tokens[0].kind, SyntaxKind::Ident);
    assert_eq!(tokens[0].text, "foo");
    assert_eq!(tokens[1].kind, SyntaxKind::Ident);
    assert_eq!(tokens[1].text, "bar");
}

#[test]
fn lex_lifetime() {
    let tokens = test_lex("'a: 'static");
    assert_eq!(tokens.len(), 3);
    assert_eq!(tokens[0].kind, SyntaxKind::Lifetime);
    assert_eq!(tokens[0].text, "'a");
    assert_eq!(tokens[1].kind, SyntaxKind::Colon);
    assert_eq!(tokens[2].kind, SyntaxKind::Lifetime);
    assert_eq!(tokens[2].text, "'static");
}

#[test]
fn lex_number_suffix_valid() {
    let tokens = test_lex("42i32 100u8 3.14f64 0xABusize");
    assert_eq!(tokens.len(), 4);
    assert_eq!(tokens[0].kind, SyntaxKind::IntLit);
    assert_eq!(tokens[0].text, "42i32");
    assert_eq!(tokens[1].kind, SyntaxKind::IntLit);
    assert_eq!(tokens[1].text, "100u8");
    assert_eq!(tokens[2].kind, SyntaxKind::FloatLit);
    assert_eq!(tokens[2].text, "3.14f64");
    assert_eq!(tokens[3].kind, SyntaxKind::IntLit);
    assert_eq!(tokens[3].text, "0xABusize");
}

// Additional number suffix validation tests (Stream S01)
use crate::lexer::LexResult;

fn lex_single(source: &str) -> LexResult {
    lex(source, FileId::from_raw(1))
}

#[test]
fn valid_i32_suffix() {
    let result = lex_single("42i32");
    assert!(result.diagnostics.is_empty(), "Expected no diagnostics, got {:?}", result.diagnostics);
    let token = result.tokens.first().expect("No token");
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "42i32");
}

#[test]
fn valid_u8_suffix() {
    let result = lex_single("255u8");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "255u8");
}

#[test]
fn valid_f64_suffix() {
    let result = lex_single("3.14f64");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::FloatLit);
    assert_eq!(token.text, "3.14f64");
}

#[test]
fn invalid_suffix_produces_error() {
    let result = lex_single("42invalid");
    assert!(!result.diagnostics.is_empty());
    let diag = &result.diagnostics[0];
    assert!(diag.message.contains("invalid number suffix") || diag.message.contains("suffix"));
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "42invalid");
}

#[test]
fn valid_i8_suffix() {
    let result = lex_single("127i8");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "127i8");
}

#[test]
fn valid_i16_suffix() {
    let result = lex_single("32767i16");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_i64_suffix() {
    let result = lex_single("9223372036854775807i64");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_isize_suffix() {
    let result = lex_single("42isize");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_u16_suffix() {
    let result = lex_single("65535u16");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_u32_suffix() {
    let result = lex_single("4294967295u32");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_u64_suffix() {
    let result = lex_single("18446744073709551615u64");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_usize_suffix() {
    let result = lex_single("42usize");
    assert!(result.diagnostics.is_empty());
}

#[test]
fn valid_f32_suffix() {
    let result = lex_single("3.14f32");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::FloatLit);
    assert_eq!(token.text, "3.14f32");
}

#[test]
fn suffix_with_underscores() {
    let result = lex_single("1_000_000i32");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "1_000_000i32");
}

#[test]
fn hex_with_suffix() {
    let result = lex_single("0xFFu8");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "0xFFu8");
}

#[test]
fn binary_with_suffix() {
    let result = lex_single("0b1010i16");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "0b1010i16");
}

#[test]
fn octal_with_suffix() {
    let result = lex_single("0o755u32");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::IntLit);
    assert_eq!(token.text, "0o755u32");
}

#[test]
fn float_with_exponent_and_suffix() {
    let result = lex_single("1.2e-3f64");
    assert!(result.diagnostics.is_empty());
    let token = result.tokens.first().unwrap();
    assert_eq!(token.kind, SyntaxKind::FloatLit);
    assert_eq!(token.text, "1.2e-3f64");
}

#[test]
fn invalid_suffix_diagnostic_span_is_correct() {
    let source = "42xyz";
    let result = lex(source, FileId::from_raw(1));
    assert_eq!(result.diagnostics.len(), 1);
    let diag = &result.diagnostics[0];
    let span = diag.span.primary;
    let lo = span.lo.to_usize();
    let hi = span.hi.to_usize();
    assert_eq!(&source[lo..hi], "xyz");
}

#[test]
fn multiple_tokens_with_invalid_suffix() {
    let result = lex_single("42invalid 123");
    assert_eq!(result.diagnostics.len(), 1);
    assert_eq!(result.tokens.len(), 2);
    assert_eq!(result.tokens[0].text, "42invalid");
    assert_eq!(result.tokens[1].text, "123");
}
