// Auto-generated by split script
mod annotation_tests;
mod comparison_tests;
mod diag_tests;
mod error_tests;
mod fixture_tests;
mod harness_tests;
mod mock_tests;
mod phase_tests;
mod property_tests;
mod ty_tests;
