use crate::LlvmBackend;
use glyim_codegen::CodegenBackend;
use std::io::Read;
use std::path::Path;

#[test]
fn s08_t21_generate_output_is_elf() {
    let backend = LlvmBackend::new();
    let output = Path::new("/tmp/glyim_test_elf_check.o");
    let body = std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
        glyim_core::CrateId::from_raw(0),
        glyim_core::LocalDefId::from_raw(100),
    )));
    let bodies = vec![body];
    let result = backend.generate(&bodies, output);
    assert!(result.is_ok(), "generate should succeed");

    let mut file = std::fs::File::open(output).expect("output file should exist");
    let mut buf = [0u8; 4];
    file.read_exact(&mut buf).expect("should read 4 bytes");
    assert_eq!(
        &buf,
        &[0x7f, 0x45, 0x4c, 0x46],
        "output should be an ELF file"
    );

    // Clean up
    std::fs::remove_file(output).ok();
}

#[test]
fn s08_t22_generate_output_non_empty() {
    let backend = LlvmBackend::new();
    let output = Path::new("/tmp/glyim_test_nonempty.o");
    let body = std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
        glyim_core::CrateId::from_raw(0),
        glyim_core::LocalDefId::from_raw(101),
    )));
    let bodies = vec![body];
    backend
        .generate(&bodies, output)
        .expect("generate should succeed");

    let metadata = std::fs::metadata(output).expect("output file should exist");
    assert!(metadata.len() > 0, "output file should not be empty");

    std::fs::remove_file(output).ok();
}

#[test]
fn s08_t23_generate_function_bytes_consistent() {
    let backend = LlvmBackend::new();
    let body = std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
        glyim_core::CrateId::from_raw(0),
        glyim_core::LocalDefId::from_raw(102),
    )));
    let r1 = backend
        .generate_function(&body)
        .expect("first call should succeed");
    let r2 = backend
        .generate_function(&body)
        .expect("second call should succeed");
    // With identical input and same context, the generated bytes should be identical
    // (deterministic codegen).
    assert_eq!(
        r1, r2,
        "generate_function should be deterministic for identical input"
    );
}

#[test]
fn s08_t24_many_functions_no_oom() {
    let backend = LlvmBackend::new();
    for i in 0..200 {
        let body = std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
            glyim_core::CrateId::from_raw(0),
            glyim_core::LocalDefId::from_raw(i as u32),
        )));
        let result = backend.generate_function(&body);
        assert!(
            result.is_ok(),
            "generate_function should succeed for many iterations"
        );
    }
}

#[test]
fn s08_t25_generate_after_many_functions() {
    let backend = LlvmBackend::new();
    // Call generate_function many times first
    for i in 0..50 {
        let body = std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
            glyim_core::CrateId::from_raw(0),
            glyim_core::LocalDefId::from_raw(i as u32),
        )));
        backend.generate_function(&body).unwrap();
    }
    // Then call generate with a batch
    let output = Path::new("/tmp/glyim_test_after_functions.o");
    let bodies: Vec<_> = (0..10)
        .map(|i| {
            std::sync::Arc::new(glyim_mir::Body::dummy(glyim_core::DefId::new(
                glyim_core::CrateId::from_raw(0),
                glyim_core::LocalDefId::from_raw(1000 + i as u32),
            )))
        })
        .collect();
    let result = backend.generate(&bodies, output);
    assert!(
        result.is_ok(),
        "generate after many generate_function calls should succeed"
    );
    assert!(output.exists());
    std::fs::remove_file(output).ok();
}

#[test]
fn s08_t26_name_is_static() {
    let b1 = LlvmBackend::new();
    let b2 = LlvmBackend::new();
    let name1 = b1.name();
    let name2 = b2.name();
    assert_eq!(name1, name2);
    // The string slice should be static (same pointer across instances)
    assert!(
        std::ptr::eq(name1, name2),
        "name() should return a static string slice"
    );
}
