[package]
name = "glyim-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Language Server Protocol implementation for Glyim"

[dependencies]
notify = "6.1"
crossbeam-channel = "0.5"
glyim-db = { path = "../glyim-db" }
glyim-hir = { path = "../glyim-hir" }
glyim-diag = { path = "../glyim-diag" }
glyim-syntax = { path = "../glyim-syntax" }
glyim-frontend = { path = "../glyim-frontend" }
glyim-core = { path = "../glyim-core" }
glyim-span = { path = "../glyim-span" }
async-lsp = { git = "https://github.com/elcoosp/async-lsp", features = ["omni-trait", "stdio", "tokio"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
dashmap = "6.1"
parking_lot = "0.12"
url = "2.5"
file_url = "0.3"
glyim-def-map = { workspace = true }

lsp-types = "0.97.0"
[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
glyim-test = { workspace = true }
tempfile = "3"